# Dependencies
markdown:         redcarpet
redcarpet:
  extensions: ["tables"]

highlighter:         true

# Permalinks
permalink:        /:year/:month/:day/:title/

# Setup
title:            Rotation Symmetry
tagline:          'Scala, Spark and Data Analytics'
url:              http://rotationsymmetry.github.io
shorturl:         

author:
  name:           'M W'
  url:            

paginate:         5

# Custom vars
version:          1.0.0

github:
  repo:           github.com/rotationsymmetry/rotationsymmetry.github.io

# This is the list of pages to include in the header of the website.
pages_list:       
  By Category: '/category/'
  Archive: '/archive/'
  About: '/about/'
  Feed: '/atom.xml'

# Allow URL Redirects: 
#  * https://help.github.com/articles/redirects-on-github-pages
gems:
  - jekyll-redirect-from

exclude: [vendor]
