name: Rotation Symmetry's Blog
description: Application Development and Data Analytics
meta_description: "My blog on application deveopment and data analytics with Scala and Python."

markdown: redcarpet
redcarpet:
  extensions: ["smart", "tables", "no_intra_emphasis", "fenced_code_blocks", "autolink", "strikethrough", "superscript", "with_toc_data"]
highlighter: pygments

permalink:        /:year/:month/:day/:title/
paginate: 5
baseurl: /


# Details for the RSS feed generator
url:            'blog url'
author:         'Your Name'

tag_names:
  scala:
    name: "Scala"
  spark:
    name: "Spark"
